// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jackycsl/catalog/catalog-job/internal/biz"
	"github.com/jackycsl/catalog/catalog-job/internal/conf"
	"github.com/jackycsl/catalog/catalog-job/internal/data"
	"github.com/jackycsl/catalog/catalog-job/internal/server"
	"github.com/jackycsl/catalog/catalog-job/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	catalogJobRepo := data.NewCatalogJobRepo(dataData, logger)
	catalogJobUseCase := biz.NewCatalogJobUseCase(catalogJobRepo, logger)
	catalogJob := service.NewCatalogJob(catalogJobUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, catalogJob, logger, tracerProvider)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
