// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jackycsl/catalog/bff/admin/internal/biz"
	"github.com/jackycsl/catalog/bff/admin/internal/conf"
	"github.com/jackycsl/catalog/bff/admin/internal/data"
	"github.com/jackycsl/catalog/bff/admin/internal/server"
	"github.com/jackycsl/catalog/bff/admin/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	catalogClient := data.NewCatalogServiceClient(discovery, tracerProvider)
	dataData, err := data.NewData(confData, logger, catalogClient)
	if err != nil {
		return nil, nil, err
	}
	catalogRepo := data.NewCatalogRepo(dataData, logger)
	catalogUsecase := biz.NewCatalogUsecase(catalogRepo, logger)
	shopAdmin := service.NewShopAdmin(catalogUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, auth, shopAdmin, tracerProvider, logger)
	grpcServer := server.NewGRPCServer(confServer, auth, shopAdmin, tracerProvider, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
	}, nil
}
