// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jackycsl/catalog/bff/interface/internal/biz"
	"github.com/jackycsl/catalog/bff/interface/internal/conf"
	"github.com/jackycsl/catalog/bff/interface/internal/data"
	"github.com/jackycsl/catalog/bff/interface/internal/server"
	"github.com/jackycsl/catalog/bff/interface/internal/service"
	"go.opentelemetry.io/otel/sdk/trace"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, tracerProvider *trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	catalogRepo := data.NewCatalogRepo(dataData, logger)
	catalogUsecase := biz.NewCatalogUsecase(catalogRepo, logger)
	shopInterface := service.NewShopInterface(catalogUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, shopInterface, tracerProvider, logger)
	grpcServer := server.NewGRPCServer(confServer, shopInterface, tracerProvider, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
