// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/jackycsl/catalog/catalog-job/internal/data/ent/game"
	"github.com/jackycsl/catalog/catalog-job/internal/data/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescCreatedAt is the schema descriptor for created_at field.
	gameDescCreatedAt := gameFields[4].Descriptor()
	// game.DefaultCreatedAt holds the default value on creation for the created_at field.
	game.DefaultCreatedAt = gameDescCreatedAt.Default.(func() time.Time)
	// gameDescUpdatedAt is the schema descriptor for updated_at field.
	gameDescUpdatedAt := gameFields[5].Descriptor()
	// game.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	game.DefaultUpdatedAt = gameDescUpdatedAt.Default.(func() time.Time)
}
